# Generated by Django 4.2.2 on 2023-06-15 11:03

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('vendor', models.CharField(max_length=256, verbose_name='Производитель')),
                ('weight', models.CharField(max_length=50, verbose_name='Вес')),
                ('composition', models.CharField(max_length=256, verbose_name='Состав')),
                ('comments', models.TextField(verbose_name='Примечание')),
                ('agelimit', models.DateField(max_length=256, verbose_name='Срок годности')),
                ('consimption', models.TextField(max_length=256, verbose_name='Расход')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото')),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано')),
                ('time_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлено')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('oldprice', models.FloatField(verbose_name='Старая цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryproducts', to='main.category', verbose_name='Категория')),
                ('subcategory', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='main.subcategory')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
