# Generated by Django 4.2.2 on 2023-06-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/donework', verbose_name='Фото Наших работ')),
            ],
            options={
                'verbose_name': 'Фото работ',
                'verbose_name_plural': 'Фото работ',
            },
        ),
    ]
