# Generated by Django 4.2.2 on 2023-06-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_workphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workphoto',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Наименование'),
        ),
    ]
