# Generated by Django 4.2.2 on 2023-06-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_workphoto_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Код от производителя'),
        ),
    ]
