# Generated by Django 4.2.2 on 2023-06-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_product_vendor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rrc',
            field=models.FloatField(default=0, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
