# Generated by Django 4.2.2 on 2023-06-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_product_rrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(default='', max_length=256, verbose_name='Наличие'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='pack',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='rrc',
            field=models.FloatField(verbose_name='РРЦ'),
        ),
    ]
