# Generated by Django 4.2.2 on 2023-06-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_product_oldprice_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='agelimit',
            field=models.DateField(blank=True, max_length=256, null=True, verbose_name='Срок годности'),
        ),
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Наличие'),
        ),
        migrations.AlterField(
            model_name='product',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='product',
            name='consimption',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Расход'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rrc',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='РРЦ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Вес'),
        ),
    ]
