# Generated by Django 4.2.2 on 2023-06-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_alter_product_agelimit_alter_product_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='oldprice',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Старая цена'),
        ),
    ]
