# Generated by Django 4.2.2 on 2023-06-26 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_servicecategory_alter_category_options_and_more'),
        ('cms', '0013_servicecategory_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.servicecategory', verbose_name='Категория'),
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
