# Generated by Django 4.2.2 on 2023-06-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_alter_service_service_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_code',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Код вида работ'),
        ),
    ]
