# Generated by Django 4.2.2 on 2023-06-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_workphoto_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.IntegerField(blank=True, max_length=256, null=True, verbose_name='Код от производителя'),
        ),
    ]
