# Generated by Django 4.2.2 on 2023-06-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_alter_product_vendor_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Наименование')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/slider', verbose_name='Фото')),
                ('vendor', models.CharField(blank=True, max_length=256, null=True, verbose_name='Производитель')),
                ('vendor_code_list', models.CharField(blank=True, max_length=256, null=True, verbose_name='Артикулы товаров')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала акции')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания акции')),
            ],
            options={
                'verbose_name': 'Промо акция',
                'verbose_name_plural': 'Промо акции',
                'ordering': ('expiration_date',),
            },
        ),
    ]
