# Generated by Django 4.2.2 on 2023-06-27 05:25

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_servicecategory_alter_category_options_and_more'),
        ('cms', '0018_promoslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoslider',
            name='promo_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promos', to='main.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='promoslider',
            name='promo_subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='promo_category', chained_model_field='promo_category', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код от производителя'),
        ),
    ]
