# Generated by Django 4.2.2 on 2023-06-27 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_vendor_alter_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoslider',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.vendor', verbose_name='Производитель'),
        ),
    ]
