# Generated by Django 4.2.2 on 2023-06-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_alter_promoslider_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pack',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
