# Generated by Django 4.2.2 on 2023-07-03 09:42

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_alter_product_pack'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Наименование')),
                ('pack', models.ImageField(blank=True, null=True, upload_to='images/pack', verbose_name='Упаковка')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Цена')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='product',
            name='pack',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='packprice', chained_model_field='packprice', null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.packprice'),
        ),
    ]
