# Generated by Django 4.2.2 on 2023-07-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_packprice_remove_product_price_alter_product_pack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packprice',
            old_name='name',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='packprice',
            name='pack',
        ),
        migrations.RemoveField(
            model_name='product',
            name='oldprice',
        ),
        migrations.AddField(
            model_name='packprice',
            name='oldprice',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Старая цена'),
        ),
    ]
