# Generated by Django 4.2.2 on 2023-07-03 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_rename_name_packprice_weight_remove_packprice_pack_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pack',
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.packprice', verbose_name='Упаковка / Цена'),
        ),
    ]
