# Generated by Django 4.2.2 on 2023-07-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0025_remove_product_pack_alter_product_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packprice',
            options={'verbose_name': 'Вес', 'verbose_name_plural': 'Веса'},
        ),
        migrations.AddField(
            model_name='product',
            name='pack',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Кол-ва в Упаковке'),
        ),
    ]
