# Generated by Django 4.2.2 on 2023-07-03 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_alter_packprice_options_product_pack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='cms.packprice', verbose_name='Упаковка / Цена'),
        ),
    ]
