# Generated by Django 4.2.2 on 2023-07-03 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_alter_product_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AddField(
            model_name='packprice',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cms.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='packprice',
            name='weight',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Объем'),
        ),
    ]
