# Generated by Django 4.2.2 on 2023-07-03 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0028_remove_product_weight_packprice_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packprice',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packprices', to='cms.product', verbose_name='Товар'),
        ),
    ]
