# Generated by Django 4.2.2 on 2023-07-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0030_introduction_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='inuse',
            field=models.BooleanField(default=False, verbose_name='Использовать на сайте'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logo',
            name='inuse',
            field=models.BooleanField(verbose_name='Использовать на сайте'),
        ),
    ]
