# Generated by Django 4.2.2 on 2023-07-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0031_introduction_inuse_alter_logo_inuse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/logo', verbose_name='Логотип'),
        ),
    ]
