# Generated by Django 4.2.2 on 2023-07-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0032_alter_logo_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='introduction',
            options={},
        ),
        migrations.AlterField(
            model_name='introduction',
            name='inuse',
            field=models.BooleanField(blank=True, null=True, verbose_name='Использовать на сайте'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='inuse',
            field=models.BooleanField(blank=True, null=True, verbose_name='Использовать на сайте'),
        ),
    ]
