# Generated by Django 4.2.2 on 2023-07-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0036_alter_socials_options_socials_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone1', models.CharField(blank=True, max_length=250, null=True, verbose_name='Номер телефона для контактов')),
                ('phone2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Номер телефона для контактов')),
                ('phone3', models.CharField(blank=True, max_length=250, null=True, verbose_name='Номер телефона для контактов')),
                ('address1', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес')),
                ('address2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес')),
                ('address3', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Контактные данные',
                'verbose_name_plural': 'Контактные данные',
            },
        ),
        migrations.AlterField(
            model_name='socials',
            name='social_network',
            field=models.CharField(choices=[('IG', 'Instagram'), ('FB', 'Facebook'), ('VK', 'VK'), ('TG', 'Telegram'), ('WA', 'Whatsapp')], max_length=30, verbose_name='Соцсеть'),
        ),
    ]
