# Generated by Django 4.2.2 on 2023-07-07 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0037_contacts_alter_socials_social_network'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packprice',
            options={'ordering': ('price',), 'verbose_name': 'Вес', 'verbose_name_plural': 'Веса'},
        ),
    ]
