# Generated by Django 4.2.2 on 2023-07-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0038_alter_packprice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='email1',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='email2',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='email3',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
    ]
