# Generated by Django 4.2.2 on 2023-07-12 12:45

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_page'),
        ('cms', '0040_rename_promo_category_promoslider_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoslider',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subcategory'),
        ),
    ]
