# Generated by Django 4.2.2 on 2023-07-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_alter_promoslider_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promoslider',
            name='vendor_code_list',
        ),
        migrations.AddField(
            model_name='promoslider',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Описание'),
        ),
    ]
