# Generated by Django 4.2.2 on 2023-07-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0046_services_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/donework', verbose_name='Фото Вида работ'),
        ),
    ]
