# Generated by Django 4.2.2 on 2023-07-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0048_ourphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='services_files',
            name='inuse',
            field=models.BooleanField(blank=True, null=True, verbose_name='Использовать на сайте'),
        ),
    ]
