# Generated by Django 4.2.2 on 2023-07-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0049_services_files_inuse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services_calculation_cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(blank=True, max_length=256, null=True, verbose_name='Дом')),
                ('apartment', models.CharField(blank=True, max_length=256, null=True, verbose_name='Квартира')),
                ('plant', models.CharField(blank=True, max_length=256, null=True, verbose_name='Промышленное помещение')),
                ('inuse', models.BooleanField(blank=True, null=True, verbose_name='Использовать на сайте')),
            ],
            options={
                'verbose_name': 'Стоимость работ для калькулятора',
                'verbose_name_plural': 'Стоимости работ для калькулятора',
            },
        ),
    ]
