# Generated by Django 4.2.2 on 2023-07-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0050_services_calculation_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/ourteam', verbose_name='Наши фото'),
        ),
    ]
