# Generated by Django 4.2.2 on 2023-07-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0052_product_pcs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pcs',
        ),
        migrations.AddField(
            model_name='product',
            name='unitofmeasure',
            field=models.CharField(blank=True, choices=[('шт', 'шт'), ('л', 'л'), ('упаковка', 'упаковка')], max_length=30, null=True, verbose_name='Единица измерения'),
        ),
    ]
