# Generated by Django 4.2.2 on 2023-08-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0053_remove_product_pcs_product_unitofmeasure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packprice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
    ]
