# Generated by Django 4.2.2 on 2023-08-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0054_alter_packprice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packprice',
            name='oldprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена'),
        ),
    ]
