# Generated by Django 4.2.2 on 2023-08-04 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0055_alter_packprice_oldprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoslider',
            name='promoproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.product', verbose_name='Акционный товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unitofmeasure',
            field=models.CharField(blank=True, choices=[('шт.', 'шт.'), ('л.', 'л.'), ('уп.', 'уп.')], max_length=30, null=True, verbose_name='Единица измерения'),
        ),
    ]
