# Generated by Django 4.2.2 on 2023-08-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0057_product_photo1_product_photo2_product_photo3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='youtubelink',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
