# Generated by Django 4.2.2 on 2023-06-20 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_slug_subcategory_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('name',), 'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='slug',
        ),
    ]
