# Generated by Django 4.2.2 on 2023-06-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_servicecategory_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/service_category', verbose_name='Фото'),
        ),
    ]
