# Generated by Django 4.2.2 on 2023-07-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_category_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/category', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/subcategory', verbose_name='Фото'),
        ),
    ]
