# Generated by Django 4.2.2 on 2023-06-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_orderitems_order_alter_orderitems_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тип Заказа'),
        ),
    ]
