# Generated by Django 4.2.2 on 2023-06-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_orderitems_image_alter_orderitems_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Стоимость'),
        ),
    ]
