# Generated by Django 4.2.2 on 2023-06-26 05:41

import crm.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0012_alter_orderitems_options_commentcrm_comment_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentcrm',
            name='comment_owner',
            field=models.ForeignKey(blank=True, default=crm.models.logged_user, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Оставил комментарий'),
        ),
    ]
