# Generated by Django 4.2.2 on 2023-06-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
