# Generated by Django 4.2.2 on 2023-07-06 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0034_alter_introduction_options'),
        ('crm', '0016_alter_order_order_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='weight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='cms.packprice', verbose_name='Вес'),
        ),
    ]
