# Generated by Django 4.2.2 on 2023-07-06 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_orderitems_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='price',
        ),
    ]
