# Generated by Django 4.2.2 on 2023-07-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_remove_orderitems_cost_remove_orderitems_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Цена'),
        ),
    ]
