# Generated by Django 4.2.2 on 2023-07-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_orderitems_cost_orderitems_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='image',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='vendor_code',
        ),
    ]
